#!/bin/bash

export vimwiki_path="$HOME/doc/personal-notes"

function note_fn() {
  if [[ "$1" == "" ]]; then
    cd "$vimwiki_path" && nvim -c "e index.md" .
  elif [[ "$2" == "" ]]; then
    cd "$vimwiki_path" && nvim -c "e $1.md" .
  else
    tags=":"
    for tag in "${@:2}"; do
      tags="$tags$tag:"
    done
    cd "$vimwiki_path" && nvim -c "e $1.md | execute 'normal ggO$tags'" .
  fi
}
alias note=note_fn
